// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $cart from "./routes/cart.tsx";
import * as $checkout from "./routes/checkout.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $products_id_ from "./routes/products/[id].tsx";
import * as $register from "./routes/register.tsx";
import * as $Add from "./islands/Add.tsx";
import * as $Carro from "./islands/Carro.tsx";
import * as $CartPrice from "./islands/CartPrice.tsx";
import * as $CitySelect from "./islands/CitySelect.tsx";
import * as $CountrySelect from "./islands/CountrySelect.tsx";
import * as $Decrease from "./islands/Decrease.tsx";
import * as $NumCarrito from "./islands/NumCarrito.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/cart.tsx": $cart,
    "./routes/checkout.tsx": $checkout,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/products/[id].tsx": $products_id_,
    "./routes/register.tsx": $register,
  },
  islands: {
    "./islands/Add.tsx": $Add,
    "./islands/Carro.tsx": $Carro,
    "./islands/CartPrice.tsx": $CartPrice,
    "./islands/CitySelect.tsx": $CitySelect,
    "./islands/CountrySelect.tsx": $CountrySelect,
    "./islands/Decrease.tsx": $Decrease,
    "./islands/NumCarrito.tsx": $NumCarrito,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
